// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnRx-P0Bqq4m5zCGvmi24ILjSt6Abp5Ak',
    appId: '1:477957133740:web:a9507fd8e5dc7bd225d609',
    messagingSenderId: '477957133740',
    projectId: 'medical-flutter--app',
    authDomain: 'medical-flutter--app.firebaseapp.com',
    storageBucket: 'medical-flutter--app.firebasestorage.app',
    measurementId: 'G-QYD0FDFWLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj1C7FfHcUXvaRMdsU_tKDWrYwz_MU20U',
    appId: '1:477957133740:android:260525788be252e525d609',
    messagingSenderId: '477957133740',
    projectId: 'medical-flutter--app',
    storageBucket: 'medical-flutter--app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGFZg8SAypkzpVc1OUy0Gu_i4CfTdLmLY',
    appId: '1:477957133740:ios:f255a88b61d95b0925d609',
    messagingSenderId: '477957133740',
    projectId: 'medical-flutter--app',
    storageBucket: 'medical-flutter--app.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGFZg8SAypkzpVc1OUy0Gu_i4CfTdLmLY',
    appId: '1:477957133740:ios:f255a88b61d95b0925d609',
    messagingSenderId: '477957133740',
    projectId: 'medical-flutter--app',
    storageBucket: 'medical-flutter--app.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnRx-P0Bqq4m5zCGvmi24ILjSt6Abp5Ak',
    appId: '1:477957133740:web:b0a35cc1b4db6c8d25d609',
    messagingSenderId: '477957133740',
    projectId: 'medical-flutter--app',
    authDomain: 'medical-flutter--app.firebaseapp.com',
    storageBucket: 'medical-flutter--app.firebasestorage.app',
    measurementId: 'G-HQ114DZSRX',
  );
}
